#!/bin/bash
### BEGIN INIT INFO
# Provides:             sidekiq
# Required-Start:       $local_fs $remote_fs
# Required-Stop:        $local_fs $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Simple, efficient background processing for Ruby.
# Description:          Sidekiq - a Redis-backed Ruby library for creating background jobs, placing those jobs on multiple queues, and processing them later.
### END INIT INFO
#
# Put this file in /etc/init.d/
#
# User-specified exit parameters used in this script:
#
# Exit Code 5 - Incorrect User ID
# Exit Code 6 - Directory not found

APP_NAME=railstom
APP_DEFAULT_ENV=production
APP_DIR=/home/rubyuser/rails_apps/${APP_NAME}-${APP_DEFAULT_ENV}/current
APP_CONFIG=${APP_DIR}/config/sidekiq.yml
LOG_FILE=$APP_DIR/log/sidekiq_${APP_DEFAULT_ENV}.log
LOCK_FILE=$APP_DIR/tmp/pids/sidekiq-${APP_NAME}-${APP_DEFAULT_ENV}.lock
PID_FILE=$APP_DIR/tmp/pids/sidekiq-${APP_NAME}-${APP_DEFAULT_ENV}.pid
GEMFILE=$APP_DIR/Gemfile
SIDEKIQ=sidekiq
BUNDLE=bundle

START_CMD="$BUNDLE exec $SIDEKIQ -e $APP_DEFAULT_ENV -P $PID_FILE -C $APP_CONFIG -L $LOG_FILE -d"
RETVAL=0


start() {
  status

  if [ $? -eq 1 ]; then
    [ `id -u` == '0' ] || (echo "$SIDEKIQ runs as root only."; exit 5)
    [ -d $APP_DIR ] || (echo "$APP_DIR not found! Exiting."; exit 6)
    echo "Starting $SIDEKIQ message processor..."
    su -l -c "cd $APP_DIR && $START_CMD" rubyuser >/dev/null 2>&1
    RETVAL=$?
    # Sleeping for 8 seconds for process to be precisely visible in process table - see status ()
    sleep 8
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    return $RETVAL
  else
    echo "$SIDEKIQ message processor is already running..."
  fi
}

stop() {
  echo "Stopping $SIDEKIQ message processor..."
  SIG="INT"
  kill -$SIG `cat $PID_FILE`
  RETVAL=$?
  [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
  return $RETVAL
}


status() {
  ps -ef | egrep "sidekiq [0-9]+.[0-9]+.[0-9]+ ${APP_NAME}-${APP_DEFAULT_ENV}" | grep -v grep
  return $?
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload)
    stop
    sleep 3
    start
    ;;
  status)
    status

    if [ $? -eq 0 ]; then
       echo "$SIDEKIQ message processor is running..."
       RETVAL=0
     else
       echo "$SIDEKIQ message processor is stopped."
       RETVAL=1
     fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 0
    ;;
esac
exit $RETVAL
